<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BooksSeeder extends Seeder
{
    /**
     * Ejecuta el seeder.
     */
    public function run(): void
    {
        $books = [
            [
                'isbn' => '978-8401032424',
                'key_title' => 'book_title juego_de_tronos',
                'author' => 'George R.R. Martin',
                'key_description' => 'book_desc juego_de_tronos',
                'price' => 27.90,
                'publisher' => 'PLAZA & JANES',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/917izhhQjIL._SL1500_.jpg',
                'subcategory_id' => 1,
            ],
            [
                'isbn' => '978-8401032431',
                'key_title' => 'book_title choque_de_reyes',
                'author' => 'George R.R. Martin',
                'key_description' => 'book_desc choque_de_reyes',
                'price' => 26.50,
                'publisher' => 'PLAZA & JANES',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91CVf1zD2qL._SL1500_.jpg',
                'subcategory_id' => 1,
            ],
            [
                'isbn' => '978-8478884452',
                'key_title' => 'book_title harry_potter_y_la_piedra_filosofal',
                'author' => 'J.K. Rowling',
                'key_description' => 'book_desc harry_potter_y_la_piedra_filosofal',
                'price' => 16.95,
                'publisher' => 'SALAMANDRA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91R1AixEiLL._SL1500_.jpg',
                'subcategory_id' => 2,
            ],
            [
                'isbn' => '978-8478884957',
                'key_title' => 'book_title harry_potter_y_la_camara_secreta',
                'author' => 'J.K. Rowling',
                'key_description' => 'book_desc harry_potter_y_la_camara_secreta',
                'price' => 17.95,
                'publisher' => 'SALAMANDRA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91voauWrUKL._SL1500_.jpg',
                'subcategory_id' => 2,
            ],
            [
                'isbn' => '978-8478885190',
                'key_title' => 'book_title harry_potter_y_el_prisionero_de_azkaban',
                'author' => 'J.K. Rowling',
                'key_description' => 'book_desc harry_potter_y_el_prisionero_de_azkaban',
                'price' => 18.00,
                'publisher' => 'SALAMANDRA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/81k9yx9N5+L._SL1500_.jpg',
                'subcategory_id' => 2,
            ],
            [
                'isbn' => '978-8478886456',
                'key_title' => 'book_title harry_potter_y_el_caliz_de_fuego',
                'author' => 'J.K. Rowling',
                'key_description' => 'book_desc harry_potter_y_el_caliz_de_fuego',
                'price' => 23.00,
                'publisher' => 'SALAMANDRA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91a2FifMS8L._SL1500_.jpg',
                'subcategory_id' => 2,
            ],
            [
                'isbn' => '978-8478887422',
                'key_title' => 'book_title harry_potter_y_la_orden_del_fenix',
                'author' => 'J.K. Rowling',
                'key_description' => 'book_desc harry_potter_y_la_orden_del_fenix',
                'price' => 24.65,
                'publisher' => 'SALAMANDRA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/81g9SrF8P1L._SL1500_.jpg',
                'subcategory_id' => 2,
            ],
            [
                'isbn' => '978-8478889907',
                'key_title' => 'book_title harry_potter_y_el_misterio_del_principe',
                'author' => 'J.K. Rowling',
                'key_description' => 'book_desc harry_potter_y_el_misterio_del_principe',
                'price' => 21.80,
                'publisher' => 'SALAMANDRA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91dBlchXbmL._SL1500_.jpg',
                'subcategory_id' => 2,
            ],
            [
                'isbn' => '978-8498381405',
                'key_title' => 'book_title harry_potter_y_las_reliquias_de_la_muerte',
                'author' => 'J.K. Rowling',
                'key_description' => 'book_desc harry_potter_y_las_reliquias_de_la_muerte',
                'price' => 23.95,
                'publisher' => 'SALAMANDRA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/815qt8aUvRL._SL1500_.jpg',
                'subcategory_id' => 2,
            ],
            [
                'isbn' => '978-8445012796 ',
                'key_title' => 'book_title el_silmarillion',
                'author' => 'J.R.R. Tolkien',
                'key_description' => 'book_desc el_silmarillion',
                'price' => 22.95,
                'publisher' => 'MINOTAURO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91wA4QqjNDL._SL1500_.jpg',
                'subcategory_id' => 3,
            ],
            [
                'isbn' => '978-8445012802',
                'key_title' => 'book_title el_hobbit',
                'author' => 'J.R.R. Tolkien',
                'key_description' => 'book_desc el_hobbit',
                'price' => 20.95,
                'publisher' => 'MINOTAURO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/9116F++x55L._SL1500_.jpg',
                'subcategory_id' => 3,
            ],
            [
                'isbn' => '978-8445009598',
                'key_title' => 'book_title el_senor_de_los_anillos_la_comunidad_del_anillo',
                'author' => 'J.R.R. Tolkien',
                'key_description' => 'book_desc el_senor_de_los_anillos_la_comunidad_del_anillo',
                'price' => 22.95,
                'publisher' => 'MINOTAURO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91ddMPYKaYL._SL1500_.jpg',
                'subcategory_id' => 3,
            ],
            [
                'isbn' => '978-8445009604',
                'key_title' => 'book_title el_senor_de_los_anillos_las_dos_torres',
                'author' => 'J.R.R. Tolkien',
                'key_description' => 'book_desc el_senor_de_los_anillos_las_dos_torres',
                'price' => 22.95,
                'publisher' => 'MINOTAURO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/81G3hXIlgfL._SL1500_.jpg',
                'subcategory_id' => 3,
            ],
            [
                'isbn' => '978-84459611',
                'key_title' => 'book_title el_senor_de_los_anillos_el_retorno_del_rey',
                'author' => 'J.R.R. Tolkien',
                'key_description' => 'book_desc el_senor_de_los_anillos_el_retorno_del_rey',
                'price' => 22.95,
                'publisher' => 'MINOTAURO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91CZONTFNgL._SL1500_.jpg',
                'subcategory_id' => 3,
            ],
            [
                'isbn' => '978-84982549',
                'key_title' => 'book_title el_caballero_de_la_armadura_oxidada',
                'author' => 'Robert Fisher',
                'key_description' => 'book_desc el_caballero_de_la_armadura_oxidada',
                'price' => 9.95,
                'publisher' => 'OBELISCO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91Q6zQ1ZJDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '98-8408060633',
                'key_title' => 'book_title el_alquimista',
                'author' => 'Paulo Coelho',
                'key_description' => 'book_desc el_alquimista',
                'price' => 9.95,
                'publisher' => 'PLANETA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91wv1ZTzZDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '98-6074802023',
                'key_title' => 'book_title el_poder_del_metabolismo',
                'author' => 'Frank Suárez',
                'key_description' => 'book_desc el_poder_del_metabolismo',
                'price' => 19.95,
                'publisher' => 'GRIJALBO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91Q6zQ1ZJDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '978-479536442',
                'key_title' => 'book_title el_poder_del_ahora',
                'author' => 'Eckhart Tolle',
                'key_description' => 'book_desc el_poder_del_ahora',
                'price' => 9.95,
                'publisher' => 'GAIA',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91wv1ZTzZDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '97-479536442',
                'key_title' => 'book_title el_secreto',
                'author' => 'Rhonda Byrne',
                'key_description' => 'book_desc el_secreto',
                'price' => 9.95,
                'publisher' => 'URANO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91Q6zQ1ZJDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '978-604802023',
                'key_title' => 'book_title el_poder',
                'author' => 'Rhonda Byrne',
                'key_description' => 'book_desc el_poder',
                'price' => 9.95,
                'publisher' => 'GRIJALBO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91wv1ZTzZDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '978-8495364a42',
                'key_title' => 'book_title el_poder_de_la_mente_subconsciente',
                'author' => 'Joseph Murphy',
                'key_description' => 'book_desc el_poder_de_la_mente_subconsciente',
                'price' => 9.95,
                'publisher' => 'URANO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91Q6zQ1ZJDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '978-6074802023',
                'key_title' => 'book_title el_poder_de_la_intencion',
                'author' => 'Wayne Dyer',
                'key_description' => 'book_desc el_poder_de_la_intencion',
                'price' => 9.95,
                'publisher' => 'GRIJALBO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91wv1ZTzZDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '978-8479a536442',
                'key_title' => 'book_title el_poder_de_los_habitos',
                'author' => 'Charles Duhigg',
                'key_description' => 'book_desc el_poder_de_los_habitos',
                'price' => 9.95,
                'publisher' => 'URANO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91Q6zQ1ZJDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '978-607482023',
                'key_title' => 'book_title el_poder_de_la_esperanza',
                'author' => 'Wayne Dyer',
                'key_description' => 'book_desc el_poder_de_la_esperanza',
                'price' => 9.95,
                'publisher' => 'GRIJALBO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91wv1ZTzZDL.jpg',
                'subcategory_id' => 4,
            ],
            [
                'isbn' => '978-847953642',
                'key_title' => 'book_title el_poder_de_la_palabra',
                'author' => 'Florence Scovel Shinn',
                'key_description' => 'book_desc el_poder_de_la_palabra',
                'price' => 9.95,
                'publisher' => 'URANO',
                'language' => 'es',
                'image' => 'https://m.media-amazon.com/images/I/91Q6zQ1ZJDL.jpg',
                'subcategory_id' => 4,
            ]
        ];


        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
